language: csharp
solution: ./AsterNET.ARI.sln
matrix:
    include:
        - dotnet: 1.0.0-preview2-003131
          mono: none
          env: DOTNETCORE=1
          install:
            - nuget -Source "https://www.nuget.org/api/v2/;https://www.myget.org/F/restsharp-portable/api/v3/index.json" restore AsterNET.ARI.sln
        - mono: latest