language: csharp
sudo: required
dist: trusty
matrix:
    include:
        - dotnet: 1.0.0-preview2-003121
          mono: latest
          env: DOTNETCORE=1
          install:
            - dotnet restore --configfile "nuget.config"
        - mono: latest
          install:
            - nuget restore AsterNET.ARI.sln -source "https://www.nuget.org/api/v2/;https://www.myget.org/F/restsharp-portable/api/v3/index.json"