language: csharp
sudo: required
dist: trusty
matrix:
    include:
        - dotnet: 1.0.1
          mono: latest
          env: DOTNETCORE=1
          install:
            - dotnet restore AsterNET.ARI.NetStandard/AsterNET.ARI.NetStandard.csproj
            - dotnet restore AsterNET.ARI/AsterNET.ARI.csproj
          script:
            - dotnet build AsterNET.ARI -c Release
            - dotnet publish AsterNET.ARI -c Release
            - dotnet build AsterNET.ARI.NetStandard -c Release
            - dotnet publish AsterNET.ARI.NetStandard -c Release