language: csharp
sudo: required
dist: trusty
matrix:
    include:
        - dotnet: 1.0.0-preview2-003121
          mono: latest
          env: DOTNETCORE=1
          install:
            - dotnet restore --configfile "nuget.config" AsterNET.ARI.NetCore1/project.json
            - dotnet restore --configfile "nuget.config" AsterNET.ARI/project.json
          script:
            - dotnet build AsterNET.ARI
            - dotnet publish AsterNET.ARI
            - dotnet build AsterNET.ARI.NetCore1
            - dotnet publish AsterNET.ARI.NetCore1